SELECT [INCIDENT_NUMBER], [CALL_TIME], [FINANCIAL_YEAR], [ERS_TYPE], [EASTING], [NORTHING]
FROM [BIHUB].[V_Measure_ERS]
WHERE 
--[ERS_TYPE] = 'Dwelling' 
--AND [FINANCIAL_YEAR] = '2020/21' 
[CALL_TIME] >= '20180401'
AND [CALL_TIME] < '20200401'
--AND [CALL_TIME] <= DATEADD(S,-1,DATEADD(MONTH, DATEDIFF(MONTH, -1, GETDATE())-1, 0))
AND [PASS_FAIL] = 0